### ISSUE TITLE
Error getting a field of DisplayMetrics.class

### ISSUE THREAD

**Issue by metc** [htormey/AndroidFacebookImageCache#1]
Unable to load the mDensityDpi Field of the DisplayMetrics class.
I think it should be "densityDpi" and not mDensityDpi.

FacebookImageLoader.java line 426: 
reflectedDensityDpi = DisplayMetrics.class.getDeclaredField("mDensityDpi").getInt(metrics);

Tested on a HTC Desire Andoroid 2.2

**Comment by htormey** [comment]
Thanks, will look into it.
